2021-07-24 01:35:26,344 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 01:40:42,465 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 22:08:30,953 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 22:12:51,199 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 22:13:15,195 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 22:13:42,955 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 22:13:56,333 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 22:20:44,226 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 22:20:55,515 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 22:21:00,907 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 23:25:36,033 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-24 23:25:39,445 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-25 00:07:07,096 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-25 00:07:44,506 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-25 00:09:40,248 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-25 00:11:35,480 INFO: Microblog startup [in D:\python_project\flask_example\venv\microblog\app\__init__.py:51]
2021-07-25 00:11:45,244 ERROR: Exception on /user/kapral26 [GET] [in d:\python_project\flask_example\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\python_project\flask_example\venv\microblog\app\routes.py", line 85, in user
    return render_template("user.html", user=user, posts=posts)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\python_project\flask_example\venv\microblog\app\templates\user.html", line 19, in template
    <p><a href="{{ url_for('follow', username=user.username }}">Follow</a></p>
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2021-07-25 00:12:25,003 ERROR: Exception on /user/kapral26 [GET] [in d:\python_project\flask_example\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\python_project\flask_example\venv\microblog\app\routes.py", line 85, in user
    return render_template("user.html", user=user, posts=posts)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\python_project\flask_example\venv\microblog\app\templates\user.html", line 19, in template
    <p><a href="{{ url_for('follow', username=user.username }}">Follow</a></p>
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
2021-07-25 00:12:27,127 ERROR: Exception on /user/kapral26 [GET] [in d:\python_project\flask_example\venv\lib\site-packages\flask\app.py:1455]
Traceback (most recent call last):
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\python_project\flask_example\venv\microblog\app\routes.py", line 85, in user
    return render_template("user.html", user=user, posts=posts)
  File "d:\python_project\flask_example\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "d:\python_project\flask_example\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\python_project\flask_example\venv\microblog\app\templates\user.html", line 19, in template
    <p><a href="{{ url_for('follow', username=user.username }}">Follow</a></p>
jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'
